version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE_URL=https://your-domain.com/api
    restart: unless-stopped
    depends_on:
      - backend

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET:-your-super-secure-production-secret}
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=warehouse
      - DB_USER=warehouse_user
      - DB_PASSWORD=${DB_PASSWORD:-your-secure-db-password}
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=warehouse
      - POSTGRES_USER=warehouse_user
      - POSTGRES_PASSWORD=${DB_PASSWORD:-your-secure-db-password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./uploads:/app/uploads
    restart: unless-stopped
    ports:
      - "5432:5432"

volumes:
  postgres_data:
