version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: products_db
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d appdb"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    container_name: products_backend
    environment:
      PORT: 5000
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: app
      DB_PASSWORD: app
      DB_NAME: appdb
      CORS_ORIGIN: http://localhost:5173
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:5000"
    volumes:
      - uploads_data:/app/uploads

  frontend:
    build: ./frontend
    container_name: products_frontend
    environment:
      VITE_API_BASE_URL: http://localhost:5000
    depends_on:
      - backend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public

volumes:
  db_data:
  uploads_data:
